apiVersion: v1
kind: Service

metadata:
  name: web-service

spec:
  selector:
<<<<<<< HEAD
    app: web-ahsgdf
=======
    app: web-asd
>>>>>>> f3076a5 (Kubernetes session-14)

  ports:
    - port: 80
      targetPort: 80

  type: ClusterIP
